### ISSUE TITLE
Rational numbers are partial missing, I think?

### ISSUE THREAD

**Issue by post-rex** [VegaDeftwing/OpGuidesHugoSrc#41]
See https://github.com/VegaDeftwing/OpGuidesHugoSrc/blob/main/content/Engineering/Math/algebra.md
At Integers where right after the tip section it somehow goes into rational numbers?

I'm not sure if this is supposed to be like that, but it seems wrong?

**Comment by VegaDeftwing** [comment]
It was, thank you for the heads up!

There's an ongoing issue in either Hugo or Typora (Which I use to write OpGuides) where occasionally a section of text will be copy pasted into the wrong file randomly, I suspect one of those ate the heading and a couple of lines of text at some point. I could check the git blame, but because I occasionally have to nuke some of the repo's history for size reasons, it's a bit of pain. 

Regardless, fixed in c5b571f1d573cd52258f9fc2275491b305786035. Thank you!
