### ISSUE TITLE
Copyright Policy?

### ISSUE THREAD

**Issue by jhwgh1968** [VegaDeftwing/OpGuidesHugoSrc#9]
I am quite impressed with this guide, and would like to contribute! However, I am reluctant to, because I see no clarity on the copyright in the [only paragraph of words about it](https://opguides.info/#copyright).

Even as a non-lawyer, I would like the README to answer the following unanswered questions:

1. When a contributor opens a PR, what do they agree to?
1. Who owns the copyright on the text? Lots of contributors on their individual contributions, certain people on certain sections, or is everything given to @VegaDeftwing?
1. Can contributors license it under different, non-conflicting terms that the copyright text?
1. Are there limitations on what can be contributed by others? For example, [The Rust Book refuses to accept large changes from contributors in order to limit their copyright liability](https://github.com/rust-lang/book/issues/1283#issuecomment-425678244). (It is printed by a real book publisher with only the principle authors listed by name. Something mentioned in the copyright text as possible in the future.)
1. What attestation and/or process is required to avoid copyright infringement/plagarism?

While I would personally suggest replacing your current copyright text with a Creative Commons License (several of the flavors are very close to what you're trying to do, and they have been reviewed by actual lawyers) getting these questions answered is most important to me.

Either way, it is fortunate the the number of contributors is small at this point in time. That means very few people would have to agree to any changes/rules.

If it would help, I can open a PR with boilerplate once I get some basic answers.

(P.S. You know where I was going to contribute? The "licensing" section. :smile:)

**Comment by VegaDeftwing** [comment]
Yeah, this is rather ironic. I actually care deeply about licencing yet OpGuides has proven to be extraordinary confusing to attach a licence too, hence the current ambiguous blurb. There are three main reason for this is this, first:

> in a commercial text-book without asking permission
   If you’re from Pearson or McGraw Hill the answer is no
   If you’re from No Starch Press, have at it.

and related issues- basically, I'm okay with resale of the content here, but only with permission.

Second, some of the content on OpGuides is used with fair use in mind, but that means I need to be careful crossing that line. For example, a large portion of https://opguides.info/phil/fallacies/ is directly from Wikipedia. Some of these sources may be compatible with whatever licence I apply, but then what about the embedded tweets and YouTube videos, product images, etc? There's a lot here that is questionable that while I'm very confident falls into fair use I don't want to put a licence on and imply ownership.

Third, and most complicated, OpGuides has gotten me sponsorship and funding- this mostly works out to be a wash, as it just barely gives me any more than the cost of the domain name every year.

so, to answer your questions more directly:

> 1. When a contributor opens a PR, what do they agree to?

Rights to use whatever they wrote, in perpetuity, with the potential for it to be used commercially (both in the "I'm making money by donations" and the "I'm letting X publisher re-distribute" sense. If I did let a publisher redistribute, I would either do so for free or use any money made to improve the website itself (paying designers/artists, experts for time checking correctness, etc.) but not for personal gain

> Who owns the copyright on the text? Lots of contributors on their individual contributions, certain people on certain sections, or is everything given to VegaDeftwing?

Uhh, yeah, that's a mess too. While I know it would probably mean a CLA (as would other points here anyway) assigning it to me is probably the easier answer. Ideally, OpGuides would be its own entity, but the cost and complexity associated with that make it unreasonable. I am open to feedback on this, as there may be a better solution I haven't considered

> Can contributors license it under different, non-conflicting terms that the copyright text?

Sorry, I'm not sure what you're asking.

> Are there limitations on what can be contributed by others? For example, The Rust Book refuses to accept large changes from contributors in order to limit their copyright liability. (It is printed by a real book publisher with only the principle authors listed by name. Something mentioned in the copyright text as possible in the future.)

This is probably the biggest reason I'd want copyright assigned to me, so that large contributions can still be accepted without fear that someday the contributor will want those changes un-done

 > What attestation and/or process is required to avoid copyright infringement/plagarism?

This is something I've already attempted to deal with, as during hacktober I had multiple PRs that attempted to just rip content off another website and put it into OpGuides. I only found them from googling, as the 'voice' of the content felt more professional than I thought most contributors would use. I really don't have a good solution for this, as being an educational resource there will, inevitably, be some content that is just *fact* and will be the same across a variety of sources. There's also the problem of where anyone learns anything in the first place- If I read a few textbooks on a subject and go to write my own content, am I not infringing on the IP of at least one of those textbooks with everything I write? With educational content these lines can get very fuzzy. 

> While I would personally suggest replacing your current copyright text with a Creative Commons License (several of the flavors are very close to what you're trying to do, and they have been reviewed by actual lawyers)

CC-0 is to broad for me to be okay with, CC-BY-SA-NC is to narrow- I am okay with commercial, but only when granted. This project really needs something more custom, but then we're back to not wanting to pay a IP lawyer

> Either way, it is fortunate the the number of contributors is small at this point in time. That means very few people would have to agree to any changes/rules.

I personally know most of them, and the only one I can think of that may be an issue I was thinking about removing the contribution in full just because it's presented in a way that I don't particularly think fits OpGuides so I don't think this will be an issue at all

**Comment by VegaDeftwing** [comment]
So for users from which I'd need a sign-off (not just typo fixes) there are:
-[ ] @isopropilick (Readme, +?) - I know he's contributed content, but I can't seem to find what

-[ ] @LorenzBung (python)
-[ ] @simonsolberg (python)
-[ ] @mariyahendriksen (python)
-[ ] @TheTrooble (python)

So, the vast majority of the contributions have been to the python chapter. There were a few minor contributions from some of these people in the [Linux Shell Appendix](https://opguides.info/engineering/linux/linuxshell/) as well, but all of those were minor enough that I'm not concerned about changing the licence with them, so if worst comes to worst I can just rework the python chapter, given it's not exactly in a useful state now anyway that's fine with me. I'd still include a thank you to the contributors even if I remove their content though, as I feel that's only fair.

**Comment by VegaDeftwing** [comment]
@LorenzBung had brought up the licence in a previous issue on one of the older repos, [here](https://github.com/opinionatedguide/opinionatedguide.github.io-src/issues/22)

My perspective has changed a bit since my comment there though, as I think that this is probably a major reason OpGuides hasn't gotten much for contributors, that's why I'm more interested in fixing the problem now

**Comment by jhwgh1968** [comment]
Your reply has answered all of my questions, @VegaDeftwing. I can certainly understand why it's not easy, given how this arose from your personal notes. In fact, my "personal notes" -- without any other cut and paste from anywhere else -- was what I was thinking of contributing, heh.

But I also will until you make more progress on this. You don't need any extra ingredients in the current soup before of you.

---

In the mean time, I do have a suggestion based on other open books: split the problem into pieces, and manage them with a strategy similar to dual licensing in the FOSS community.

Step one (as you have already started doing) is to own the copyright -- and remove, re-write, or collect assignments for anything you're worried about.

To maintain total ownership, contributors of significant text would either sign a Copyright Assignment Agreement ([such as a boilerplate one from Project Harmony](http://harmonyagreements.org/guide.html)), or make a simple public domain attestation (such as [this one](https://github.com/ytdl-org/youtube-dl/blob/master/.github/PULL_REQUEST_TEMPLATE.md)). I would suggest offering both options, since some people (myself included) are leery of copyright assignment for other reasons.

<details name="Footnotes">
Since you specifically mentioned Wikipedia, my personal opinion is that the Wikipedia quotes can be shortened to a fair use length, or just plain deleted (e.g. in the Philosophy section). I personally don't see them as much more helpful than an empty subject title while waiting for a "TODO" to be filled in -- and that fill-in will clearly be much more original anyway.

</details>


Once you have ownership, you would then create two "versions" of the work (which would be nearly identical):
* **The Web Version**: This is the version of the text that is available on the web. This would be your preferred flavor of CC-NC-SA.
* **The Manuscript**: This is the "hard copy" of the text, which you would commercially license.

Here is what this means:
* 

The web version would be be licensed as Creative Commons, both Non-Commercial and Share-Alike. That is, you bind anyone who doesn't pay you to Creative Commons use. If you don't want to forgo commercial opportunities, just a note at the bottom saying "if you'd like to make money or offer a book deal, please contact me I'm open to it." But don't bend your license for that.

Instead, the manuscript would be licensed separately for commercial purposes, on an individual or group basis -- to publishers, interested parties, etc. It could also be revised based on IP lawyers of others if necessary.

**Comment by VegaDeftwing** [comment]
I assume that by making it CC-NC-SA on the web version with all content either by me, public domain, or assigned to me that I would have the right to license it commercially on a case-by-case basis as it's all work I have the rights to I'd be making an exception for?

**Comment by LorenzBung** [comment]
I don't care what you do with my commits, though I'd like to state that a) I stopped contributing because of the licensing (didn't feel like I contributed to open source) and b) the current repo seems like an utter mess :D

**Comment by VegaDeftwing** [comment]
Why do you think it's a mess? Content is pretty well divided into folders with reasonable names. The only thing "messy" imho is the static folder with images tossed into it, but the other options aren't any cleaner.

**Comment by LorenzBung** [comment]
> Why do you think it's a mess? Content is pretty well divided into folders with reasonable names. The only thing "messy" imho is the static folder with images tossed into it, but the other options aren't any cleaner. 

If I remember correctly, the page used to compile from (readable) markdown, now there's only generated html in the respective folders.
Also, there are hundereds of photos in the root folder

**Comment by VegaDeftwing** [comment]
Yeah, that's just a side effect of how Hugo and Github Pages work together- I have to have a source repo and a repo that is a mess like that.

I hope that after licensing is fixed up and now that you've seen the source repo I could convice you to contribute again!

**Comment by jhwgh1968** [comment]
> I assume that by making it CC-NC-SA on the web version with all content either by me, public domain, or assigned to me that I would have the right to license it commercially on a case-by-case basis as it's all work I have the rights to I'd be making an exception for?

That is basically correct.

That said, the way you phrased it makes me want to clarify exactly how this works. If the law is interesting to you, read on, otherwise don't worry about it.

<details>

My "point one" is about getting unrestricted rights to everything, allowing you to make "copies" and "versions" however you please.

* Your words you wrote by default.
* You own the words in PRs assigned to you explicitly via CAA.
* The public domain, in my non-lawyer understanding, is best described as "everyone owns it", so you "own" that too.
* If you stay within the lines of fair use (a subject far beyond my non-lawyer expertise) you can make reproductions, even commercially, without obtaining ownership or permission.

The CC-NA-SA licensing is not part of the ownership itself, merely one aspect in which you exercise it. That license is to protect the spirit of community and openness with which you wrote the document.

I chose something much narrower than your complete "terms" on the site, because website source is on GitHub. My non-lawyer understanding is **anyone who forks the repo** is "making a copy" in the eyes of copyright lawyers.

You can see how that would get legally messy real quick! If they simply start committing their own changes -- even if they don't set up their own website -- they need to be bound to *something*, both for their legal protection and yours.

My recommendation of CC-NC-SA is really a way to set a baseline rule: if you don't talk to me and do your own thing, you must maintain the spirit of community and openness, which was my intent when I shared it with you.

That does not exclude anything else, such as: if you do talk to me, we can work something out, commercial or otherwise.

Hopefully that makes sense.
</details>

**Comment by VegaDeftwing** [comment]
More contributions have been removed in ad87198e23e1ec810dd98965559eebaffb9c655e

@jhwgh1968 I've decided that I'll probably just say put a tiny contributors agreement into PRs that says something along the lines of the project is CC-NC-SA, so by contributing you also agree to share your content under the same licence, **but** that I (Vega) may collect some donations from the site though platforms such as Github Sponsors or directly via Venmo. (right now this is barely above paying for the domain name anyway) Other than that, no weirdness. I really doubt anyone will ever want to put this project into print, and frankly, I don't think it ever could be due to how much it relies on outside links and embeds. The point of OpGuides was to make a 'textbook' that acknowledges the strengths of the internet coming together - no print version could ever replicate that. So heck it, I'll make it fully open.

I also noticed @jamespeapen has made a fair amount of contributions, so James, if you read this, are you down for a proper re-licence to CC-NC-SA? I've already put your name into the Contributiors section on the homepage as well.

**Comment by VegaDeftwing** [comment]
![image](https://user-images.githubusercontent.com/11283620/132792670-87224f23-deaa-4ae3-9149-de6b3a286e6b.png)

Here's what I'm currently thinking. It's still a tad awkward, but I can't think of a better way to handle it

**Comment by VegaDeftwing** [comment]
@soatok has agreed to be "The Backup" under this proposal

![image](https://user-images.githubusercontent.com/11283620/132799048-cc0fe03b-c12f-4687-9b60-3d271c89594c.png)

Here is where it stands now, I think these exceptions are all reasonable. in b1ad114e354301f652832f79f72dcc7d7ee9ef67 I have made my best effort to move all assets that relate to the exceptions into `/static/nonfree/`

**Comment by VegaDeftwing** [comment]
I have pushed this (with a few minor fixes) to the live page, as well as made a [PR template with multiple options for licensing](https://github.com/VegaDeftwing/OpGuidesHugoSrc/blob/main/pull_request_template.md)

I've done my best to do this in a way that makes everyone happy while not screwing myself over- I don't want to *lose* money on OpGuides, and the contributions I'm receiving currently ensure that by more than covering the cost of the domain name. I also want to be sure anyone that forks OpGuides has that same option in the future, provided they have shown at least some effort to make the site their own (removed the content that I retain my copyright on and add at least some of their own) hence leaving the decision up to myself or the person appointed on my behalf. I realize this is a bit against the open source spirit and places a large amount of trust in me; however, I really couldn't find a better solution.

**Comment by jhwgh1968** [comment]
Thanks @VegaDeftwing! I just created a draft PR to check out your boilerplate, and it's good enough for me. It'll be a while before I get my contribution hammered out, but I'll definitely be back.

As a final note:
> I'll be leaving this issue open permanently as a place for conversation to take place again should it be necessary

In that case, perhaps [pin the issue](https://help.github.com/articles/pinning-an-issue-to-your-repository/) as well?

**Comment by VegaDeftwing** [comment]
Given this hasn't been an issue in a while now, I'm going to close this.
